// <auto-generated />
using System;
using System.Collections.Generic;
using AuraLearn.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuraLearn.Infrastructure.Migrations
{
    [DbContext(typeof(AuraLearnDbContext))]
    [Migration("20260929070000_AddTutorUserId")]
    partial class AddTutorUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuraLearn.Domain.Entities.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Credentials")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("credentials");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean")
                        .HasColumnName("featured");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PriceCrc")
                        .HasColumnType("integer")
                        .HasColumnName("price_crc");

                    b.Property<int>("PriceUsd")
                        .HasColumnType("integer")
                        .HasColumnName("price_usd");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("rating");

                    b.Property<int>("Reviews")
                        .HasColumnType("integer")
                        .HasColumnName("reviews");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.PrimitiveCollection<List<string>>("Subjects")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("subjects");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("university");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("verification_status");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_tutors_user_id");

                    b.HasIndex("VerificationStatus")
                        .HasDatabaseName("ix_tutors_verification_status");

                    b.HasIndex("University", "Rating")
                        .HasDatabaseName("ix_tutors_university_rating");

                    b.ToTable("tutors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3301"),
                            Bio = "8 años de experiencia en tutoría universitaria. Metodología orientada a resultados.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "PhD Matemáticas",
                            Featured = true,
                            Name = "Dr. Carlos Solano",
                            PriceCrc = 14500,
                            PriceUsd = 28,
                            Rating = 4.98m,
                            Reviews = 184,
                            Subjects = new List<string> { "Cálculo I", "Cálculo II", "Álgebra Lineal", "EDOs" },
                            University = "UCR",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3302"),
                            Bio = "Especialista en preparación técnica para entrevistas en big tech.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "M.Sc. Computación",
                            Featured = true,
                            Name = "Ing. Sofía Hernández",
                            PriceCrc = 16000,
                            PriceUsd = 31,
                            Rating = 5.00m,
                            Reviews = 92,
                            Subjects = new List<string> { "Python", "Algoritmos", "Estructuras de Datos", "IA" },
                            University = "TEC",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3303"),
                            Bio = "Profesor agregado UCR. Enfoque práctico con más de 500 estudiantes ayudados.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "M.Sc. Física",
                            Featured = false,
                            Name = "Prof. David Morales",
                            PriceCrc = 12000,
                            PriceUsd = 23,
                            Rating = 4.90m,
                            Reviews = 115,
                            Subjects = new List<string> { "Física I", "Física II", "Termodinámica", "Mecánica" },
                            University = "UCR",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3304"),
                            Bio = "Investigadora postdoctoral. Especialista en química orgánica para carreras de salud.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "PhD Química",
                            Featured = false,
                            Name = "Dra. Marcela Vargas",
                            PriceCrc = 15000,
                            PriceUsd = 29,
                            Rating = 4.95m,
                            Reviews = 140,
                            Subjects = new List<string> { "Química Orgánica", "Bioquímica", "Farmacología" },
                            University = "UNA",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3305"),
                            Bio = "Economista senior con experiencia en organismos internacionales.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "M.Sc. Economía",
                            Featured = false,
                            Name = "M.Sc. Javier Rodríguez",
                            PriceCrc = 13500,
                            PriceUsd = 26,
                            Rating = 4.85m,
                            Reviews = 78,
                            Subjects = new List<string> { "Econometría", "Microeconomía", "Macroeconomía", "Finanzas" },
                            University = "TEC",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3306"),
                            Bio = "Docente-investigadora con énfasis en biología molecular y genética.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "PhD Biología",
                            Featured = false,
                            Name = "Dra. Laura Prop",
                            PriceCrc = 14000,
                            PriceUsd = 27,
                            Rating = 4.92m,
                            Reviews = 103,
                            Subjects = new List<string> { "Biología Celular", "Genética", "Microbiología" },
                            University = "UCR",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3307"),
                            Bio = "Ingeniero electricista con Maestría en TEC. 6 años de experiencia.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "M.Sc. Ing. Eléctrica",
                            Featured = false,
                            Name = "Ing. Andrés González",
                            PriceCrc = 13000,
                            PriceUsd = 25,
                            Rating = 4.78m,
                            Reviews = 56,
                            Subjects = new List<string> { "Circuitos", "Electrónica", "Señales", "Control" },
                            University = "TEC",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3308"),
                            Bio = "Profesora jubilada UCR. 20 años en estadística aplicada.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "PhD Estadística",
                            Featured = false,
                            Name = "Dra. Carolina Morales",
                            PriceCrc = 15500,
                            PriceUsd = 30,
                            Rating = 4.88m,
                            Reviews = 67,
                            Subjects = new List<string> { "Estadística", "Probabilidad", "R", "Análisis de Datos" },
                            University = "UCR",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3309"),
                            Bio = "Matemático puro. Doctorado en vías. Dominio completo del cálculo avanzado.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "M.Sc. Matemáticas",
                            Featured = true,
                            Name = "M.Sc. Ricardo Fernández",
                            PriceCrc = 12500,
                            PriceUsd = 24,
                            Rating = 4.97m,
                            Reviews = 201,
                            Subjects = new List<string> { "Cálculo III", "Variable Compleja", "Topología" },
                            University = "UNA",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3310"),
                            Bio = "Preparadora certificada TOEFL. Metodología inmersiva con materiales auténticos.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "M.Sc. Lingüística",
                            Featured = false,
                            Name = "M.Sc. María Pérez",
                            PriceCrc = 11000,
                            PriceUsd = 21,
                            Rating = 4.93m,
                            Reviews = 88,
                            Subjects = new List<string> { "Inglés Académico", "TOEFL", "Redacción", "Español" },
                            University = "UCR",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3311"),
                            Bio = "Físico médico hospitalario. Prepara para exámenes de boards profesionales.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "PhD Física Médica",
                            Featured = false,
                            Name = "Dr. Jorge Torres",
                            PriceCrc = 17000,
                            PriceUsd = 33,
                            Rating = 4.81m,
                            Reviews = 44,
                            Subjects = new List<string> { "Física Médica", "Radiología", "Protección Radiológica" },
                            University = "TEC",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3312"),
                            Bio = "Ingeniera civil con maestría en estructuras. Experiencia en proyecto y supervisión.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "Ing. Civil",
                            Featured = false,
                            Name = "Ing. Ana Salas",
                            PriceCrc = 14000,
                            PriceUsd = 27,
                            Rating = 4.76m,
                            Reviews = 39,
                            Subjects = new List<string> { "Estática", "Resistencia", "Hormigón", "Diseño Estructural" },
                            University = "TEC",
                            VerificationStatus = 3
                        });
                });

            modelBuilder.Entity("AuraLearn.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AuraLearn.Domain.Entities.Tutor", b =>
                {
                    b.HasOne("AuraLearn.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tutors_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
