// <auto-generated />
using System;
using System.Collections.Generic;
using AuraLearn.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuraLearn.Infrastructure.Migrations
{
    [DbContext(typeof(AuraLearnDbContext))]
    [Migration("20261001232749_AddTutorAvailability")]
    partial class AddTutorAvailability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuraLearn.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<int?>("ComprobanteAmountCrc")
                        .HasColumnType("integer")
                        .HasColumnName("comprobante_amount_crc");

                    b.Property<string>("ComprobantePhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("comprobante_phone");

                    b.Property<DateTime?>("ComprobanteSubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("comprobante_submitted_at");

                    b.Property<string>("ConfirmationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("confirmation_number");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("decision_reason");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("PriceCrc")
                        .HasColumnType("integer")
                        .HasColumnName("price_crc");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("slot_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmationNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_reservations_confirmation_number");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_reservations_idempotency_key");

                    b.HasIndex("SlotId")
                        .IsUnique()
                        .HasDatabaseName("ux_reservations_active_slot")
                        .HasFilter("status IN (1, 2)");

                    b.HasIndex("StudentId", "CreatedAt")
                        .HasDatabaseName("ix_reservations_student_created");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("AuraLearn.Domain.Entities.Slot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("tutor_id");

                    b.HasKey("Id");

                    b.HasIndex("TutorId", "StartAt")
                        .IsUnique()
                        .HasDatabaseName("ux_slots_tutor_start");

                    b.ToTable("slots", (string)null);
                });

            modelBuilder.Entity("AuraLearn.Domain.Entities.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Credentials")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("credentials");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean")
                        .HasColumnName("featured");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PriceCrc")
                        .HasColumnType("integer")
                        .HasColumnName("price_crc");

                    b.Property<int>("PriceUsd")
                        .HasColumnType("integer")
                        .HasColumnName("price_usd");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("rating");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("Reviews")
                        .HasColumnType("integer")
                        .HasColumnName("reviews");

                    b.PrimitiveCollection<List<string>>("Subjects")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("subjects");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("university");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("verification_status");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_tutors_user_id");

                    b.HasIndex("VerificationStatus")
                        .HasDatabaseName("ix_tutors_verification_status");

                    b.HasIndex("University", "Rating")
                        .HasDatabaseName("ix_tutors_university_rating");

                    b.ToTable("tutors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3301"),
                            Bio = "8 años de experiencia en tutoría universitaria. Metodología orientada a resultados.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "PhD Matemáticas",
                            Featured = true,
                            Name = "Dr. Carlos Solano",
                            PriceCrc = 14500,
                            PriceUsd = 28,
                            Rating = 4.98m,
                            Reviews = 184,
                            Subjects = new List<string> { "Cálculo I", "Cálculo II", "Álgebra Lineal", "EDOs" },
                            University = "UCR",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3302"),
                            Bio = "Especialista en preparación técnica para entrevistas en big tech.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "M.Sc. Computación",
                            Featured = true,
                            Name = "Ing. Sofía Hernández",
                            PriceCrc = 16000,
                            PriceUsd = 31,
                            Rating = 5.00m,
                            Reviews = 92,
                            Subjects = new List<string> { "Python", "Algoritmos", "Estructuras de Datos", "IA" },
                            University = "TEC",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3303"),
                            Bio = "Profesor agregado UCR. Enfoque práctico con más de 500 estudiantes ayudados.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "M.Sc. Física",
                            Featured = false,
                            Name = "Prof. David Morales",
                            PriceCrc = 12000,
                            PriceUsd = 23,
                            Rating = 4.90m,
                            Reviews = 115,
                            Subjects = new List<string> { "Física I", "Física II", "Termodinámica", "Mecánica" },
                            University = "UCR",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3304"),
                            Bio = "Investigadora postdoctoral. Especialista en química orgánica para carreras de salud.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "PhD Química",
                            Featured = false,
                            Name = "Dra. Marcela Vargas",
                            PriceCrc = 15000,
                            PriceUsd = 29,
                            Rating = 4.95m,
                            Reviews = 140,
                            Subjects = new List<string> { "Química Orgánica", "Bioquímica", "Farmacología" },
                            University = "UNA",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3305"),
                            Bio = "Economista senior con experiencia en organismos internacionales.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "M.Sc. Economía",
                            Featured = false,
                            Name = "M.Sc. Javier Rodríguez",
                            PriceCrc = 13500,
                            PriceUsd = 26,
                            Rating = 4.85m,
                            Reviews = 78,
                            Subjects = new List<string> { "Econometría", "Microeconomía", "Macroeconomía", "Finanzas" },
                            University = "TEC",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3306"),
                            Bio = "Docente-investigadora con énfasis en biología molecular y genética.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "PhD Biología",
                            Featured = false,
                            Name = "Dra. Laura Prop",
                            PriceCrc = 14000,
                            PriceUsd = 27,
                            Rating = 4.92m,
                            Reviews = 103,
                            Subjects = new List<string> { "Biología Celular", "Genética", "Microbiología" },
                            University = "UCR",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3307"),
                            Bio = "Ingeniero electricista con Maestría en TEC. 6 años de experiencia.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "M.Sc. Ing. Eléctrica",
                            Featured = false,
                            Name = "Ing. Andrés González",
                            PriceCrc = 13000,
                            PriceUsd = 25,
                            Rating = 4.78m,
                            Reviews = 56,
                            Subjects = new List<string> { "Circuitos", "Electrónica", "Señales", "Control" },
                            University = "TEC",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3308"),
                            Bio = "Profesora jubilada UCR. 20 años en estadística aplicada.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "PhD Estadística",
                            Featured = false,
                            Name = "Dra. Carolina Morales",
                            PriceCrc = 15500,
                            PriceUsd = 30,
                            Rating = 4.88m,
                            Reviews = 67,
                            Subjects = new List<string> { "Estadística", "Probabilidad", "R", "Análisis de Datos" },
                            University = "UCR",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3309"),
                            Bio = "Matemático puro. Doctorado en vías. Dominio completo del cálculo avanzado.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "M.Sc. Matemáticas",
                            Featured = true,
                            Name = "M.Sc. Ricardo Fernández",
                            PriceCrc = 12500,
                            PriceUsd = 24,
                            Rating = 4.97m,
                            Reviews = 201,
                            Subjects = new List<string> { "Cálculo III", "Variable Compleja", "Topología" },
                            University = "UNA",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3310"),
                            Bio = "Preparadora certificada TOEFL. Metodología inmersiva con materiales auténticos.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "M.Sc. Lingüística",
                            Featured = false,
                            Name = "M.Sc. María Pérez",
                            PriceCrc = 11000,
                            PriceUsd = 21,
                            Rating = 4.93m,
                            Reviews = 88,
                            Subjects = new List<string> { "Inglés Académico", "TOEFL", "Redacción", "Español" },
                            University = "UCR",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3311"),
                            Bio = "Físico médico hospitalario. Prepara para exámenes de boards profesionales.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "PhD Física Médica",
                            Featured = false,
                            Name = "Dr. Jorge Torres",
                            PriceCrc = 17000,
                            PriceUsd = 33,
                            Rating = 4.81m,
                            Reviews = 44,
                            Subjects = new List<string> { "Física Médica", "Radiología", "Protección Radiológica" },
                            University = "TEC",
                            VerificationStatus = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3312"),
                            Bio = "Ingeniera civil con maestría en estructuras. Experiencia en proyecto y supervisión.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credentials = "Ing. Civil",
                            Featured = false,
                            Name = "Ing. Ana Salas",
                            PriceCrc = 14000,
                            PriceUsd = 27,
                            Rating = 4.76m,
                            Reviews = 39,
                            Subjects = new List<string> { "Estática", "Resistencia", "Hormigón", "Diseño Estructural" },
                            University = "TEC",
                            VerificationStatus = 3
                        });
                });

            modelBuilder.Entity("AuraLearn.Domain.Entities.TutorAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("EndLocal")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_local");

                    b.Property<TimeOnly>("StartLocal")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_local");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("tutor_id");

                    b.Property<int>("Weekday")
                        .HasColumnType("integer")
                        .HasColumnName("weekday");

                    b.HasKey("Id");

                    b.HasIndex("TutorId", "Weekday", "StartLocal")
                        .IsUnique()
                        .HasDatabaseName("ux_tutor_availability_tutor_weekday_start");

                    b.ToTable("tutor_availability", (string)null);
                });

            modelBuilder.Entity("AuraLearn.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AuraLearn.Domain.Entities.WalletEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AmountCrc")
                        .HasColumnType("integer")
                        .HasColumnName("amount_crc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_wallet_entries_user_created");

                    b.ToTable("wallet_entries", (string)null);
                });

            modelBuilder.Entity("AuraLearn.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("AuraLearn.Domain.Entities.Slot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_slots_slot_id");

                    b.HasOne("AuraLearn.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_users_student_id");

                    b.Navigation("Slot");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AuraLearn.Domain.Entities.Slot", b =>
                {
                    b.HasOne("AuraLearn.Domain.Entities.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_slots_tutors_tutor_id");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("AuraLearn.Domain.Entities.Tutor", b =>
                {
                    b.HasOne("AuraLearn.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tutors_users_user_id");
                });

            modelBuilder.Entity("AuraLearn.Domain.Entities.TutorAvailability", b =>
                {
                    b.HasOne("AuraLearn.Domain.Entities.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tutor_availability_tutors_tutor_id");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("AuraLearn.Domain.Entities.WalletEntry", b =>
                {
                    b.HasOne("AuraLearn.Domain.Entities.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_wallet_entries_reservations_reservation_id");

                    b.HasOne("AuraLearn.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_entries_users_user_id");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
